name: community-bot
services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: community-bot
    ports:
      - '5432:5432'
    volumes:
      - 'community-bot-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d community-bot
      interval: 2s
      timeout: 10s
      retries: 15
  redis:
    image: 'redis:7.2-alpine'
    ports:
      - '6379:6379'
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping || exit 1
      interval: 30s
      timeout: 20s
      retries: 5
    
volumes:
  community-bot-postgres-data: