services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/usr/src/bot
    env_file:
      - .env
    container_name: ts-node-docker
    # expose:
    #   - '4000'
    # ports:
    #   - '4000:4000'
    command: npm run dev
